//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Plugin_TerrainEditor.rc
//
#define IDB_BITMAP1                     1007
#define IDB_BITMAP2                     1008
#define IDB_BITMAP3                     1009
#define IDC_TAB1                        2000
#define IDD_TERRAIN_EDITOR              2000
#define IDC_COMBO1                      2002
#define IDD_HEIGHT_EDITOR               2002
#define IDC_SLIDER1                     2003
#define IDC_SLIDER2                     2004
#define IDD_TMEDITOR_DLG                2004
#define IDC_silderBlue                  2005
#define IDC_SLIDER4                     2006
#define IDC_SLIDER3                     2006
#define IDD_DLG_LVE                     2007
#define IDC_BUTTON3                     2008
#define IDD_AdjustColor                 2008
#define IDC_BUTTON4                     2009
#define IDC_BUTTON1                     2010
#define IDD_VEGDLG                      2010
#define IDC_BUTTON6                     2011
#define IDC_BUTTON2                     2011
#define IDD_CreateNew                   2011
#define IDC_BUTTON5                     2012
#define IDD_WATER                       2012
#define IDC_EDIT1                       2013
#define IDD_LIGHTMAP_EDIT               2013
#define IDC_BUTTON7                     2013
#define IDC_EDIT3                       2014
#define IDC_BUTTON8                     2014
#define IDC_EDIT4                       2015
#define IDD_LIGHTEDIT                   2015
#define IDC_BUTTON9                     2015
#define IDC_LIST1                       2016
#define IDC_EDIT5                       2016
#define IDD_DIALOG1                     2016
#define IDD_FOGEDIT                     2016
#define IDC_SPIN1                       2017
#define IDC_EDIT6                       2017
#define IDB_BITMAP4                     2017
#define IDC_BUTTON10                    2017
#define IDC_LIST2                       2018
#define IDC_EDIT7                       2018
#define IDB_BITMAP5                     2018
#define IDC_lblTime                     2019
#define IDB_BITMAP6                     2019
#define IDC_EDIT8                       2019
#define IDC_EDIT9                       2020
#define ID_CANCEL                       2021
#define IDC_silderRed                   2022
#define IDB_BITMAP8                     2022
#define IDC_silderGreen                 2023
#define IDC_silderAlpha                 2024
#define IDC_RADIO256                    2025
#define IDC_RADIO512                    2026
#define IDC_RANDOMBMP                   2028
#define IDC_TextureADD                  2028
#define IDC_RANDOMBMP2                  2029
#define IDC_BtnSaveLight                2029
#define IDC_BtnUpdateNorm               2030
#define IDC_SliderBrightness            2031
#define IDC_StatBrightness              2032
#define IDC_BtnFlatness                 2033
#define IDC_RandomTex                   2035
#define IDC_lblOperObj                  2036
#define IDC_RandomTex2                  2036
#define IDC_txtSensitivity              2037
#define IDC_RADIO1                      2038
#define IDC_RADIO2                      2039
#define IDC_RADIO3                      2040
#define IDC_RADIO4                      2041
#define IDC_CHECK1                      2042
#define IDC_RADIO8                      2042
#define IDC_CHECK2                      2043
#define IDC_EDIT2                       2044
#define IDC_Height                      2045
#define IDC_GREEN_EDIT                  2045
#define IDC_HeightText                  2046
#define IDC_BLUE_EDIT                   2046
#define IDC_STATICZB                    2048
#define IDC_STATICtemp3                 2049
#define IDC_STATICZB1                   2049
#define IDC_RADIO5                      2050
#define IDC_RADIO6                      2051
#define IDC_SPIN2                       2051
#define IDC_RADIO7                      2052
#define IDC_STATIC_MSG                  2052
#define IDC_PROPERTY_LIST_STATIC        2053
#define IDC_RADIO9                      2053
#define IDB_SUB                         2054
#define IDC_WATER_LIST                  2054
#define IDB_PLUS                        2055
#define IDC_COLOR_STATIC                2055
#define IDC_COLOR_BAR_STATIC            2056
#define IDC_SELECT_SIGN_STATIC          2057
#define IDC_RED_EDIT                    2058
#define IDC_PROGRESS_BAR                2059
#define IDC_PROGRESS_TEXT               2061
#define IDC_BU                          2062
#define IDC_RED_STATIC                  2063
#define IDC_GREEN_STATIC                2064
#define IDC_BLUE_STATIC                 2065
#define IDC_PREPIC                      2068
#define IDC_CHECK3                      2069
#define IDC_BUTTON11                    2070
#define IDC_FOG_COR                     2071
#define IDC_BUTTON12                    2072
#define IDC_BUTTON13                    2073
#define IDD_PROGRESS_DIALOG             2077

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2026
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2074
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
